# Generated by Django 5.0.6 on 2024-06-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='char_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='owner',
            new_name='char_owner',
        ),
    ]
