# Generated by Django 5.0.6 on 2024-07-01 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_character_char_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_name',
            new_name='character_name',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
