# Generated by Django 5.0.6 on 2024-07-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_char_name_character_character_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_owner',
            new_name='character_owner',
        ),
    ]
