# Generated by Django 5.0.6 on 2024-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_character_character_owner_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parties',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.party'),
        ),
    ]
